### ISSUE TITLE
Failed round 1 (open): Error: Error: connection not open on send()

### ISSUE THREAD

**Issue by tracywong117** [hyperledger-caliper/caliper#1409]
### Which Caliper version are you using?

v0.4.2

### Which Node.JS version are you using?

v10.24.1

### Which operating system are you using?

Ubuntu 22.04 LTS

### Please provide some context for your error. For example, when did the error occur? What were you trying to achieve, and how?

I need help. I am new to Hyperledger Besu and Caliper. 

I have set up a private QBFT network according to the tutorial on https://besu.hyperledger.org/en/stable/Tutorials/Private-Network/Create-QBFT-Network/. 

genesis.json
{
  "config" : {
    "chainId" : 1988,
    "londonBlock" : 0,
    "contractSizeLimit" : 2147483647,
    "qbft" : {
      "blockperiodseconds" : 2,
      "epochlength" : 30000,
      "requesttimeoutseconds" : 4
    }
  },
  "nonce" : "0x0",
  "timestamp" : "0x62CF8FCC",
  "gasLimit" : "0x1fffffffffffff",
  "difficulty" : "0x1",
  "mixHash" : "0x63746963616c2062797a616e74696e65206661756c7420746f6c6572616e6365",
  "coinbase" : "0x0000000000000000000000000000000000000000",
  "alloc" : {
    "fe3b557e8fb62b89f4916b721be55ceb828dbd73" : {
      "balance" : "0xad78ebc5ac6200000"
    },
    "627306090abaB3A6e1400e9345bC60c78a8BEf57" : {
      "balance" : "90000000000000000000000"
    },
    "f17f52151EbEF6C7334FAD080c5704D77216b732" : {
      "balance" : "90000000000000000000000"
    }
  },
  "extraData" : "0xf87aa00000000000000000000000000000000000000000000000000000000000000000f854945d6ba5f050de28ec17f31c7c984b00ba7ce0c8539488433109710e5e776380c31300aad3ed9c81064b94a89e86444c99a4e25bdbea5634b14f56c5be7075947aafe32ab876af19e69ac4f91a9a714032be7b7ec080c0"
}

I have run a docker for alethio/ethereum-lite-explorer to view the blockchain using this command: docker run -p 80:80 -e APP_NODE_URL="http://localhost:8545" alethio/ethereum-lite-explorer. 

I have deployed a smart contract ERC20 using truffle. 
> transaction hash:    0x98acd382d14e675651b9d93fb2053d14a9e1e959b8fcfb5504c0d6983eead815
   > Blocks: 0            Seconds: 0
   > contract address:    0x2a504B5e7eC284ACa5b6f49716611237239F0b97
   > block number:        168829
   > block timestamp:     1658138370
   > account:             0x627306090abaB3A6e1400e9345bC60c78a8BEf57
   > balance:             89999.99999999944553492
   > gas used:            859653 (0xd1e05)
   > gas price:           0.00000001 gwei
   > value sent:          0 ETH
   > total cost:          0.00000000000859653 ETH

   > Saving migration to chain.
   > Saving artifacts
   -------------------------------------
   > Total cost:     0.00000000000859653 ETH

I want to test the network and smart contract ERC20 using Caliper.

I believe the problem is the network configuration instead of the benchmark configuration.

May someone tell me if I have set some parameters in the network.json wrongly. Or how can I solve this problem?

### What was the observed incorrect behavior?

Failed round 1 (open): Error: Error: connection not open on send()

### Please provide the error logs and their surroundings.

```text
2022.07.19-14:50:03.724 info  [caliper] [cli-launch-manager] 	Set workspace path: /home/innoblock/Desktop/free-gas-besu-private
2022.07.19-14:50:03.725 info  [caliper] [cli-launch-manager] 	Set benchmark configuration path: /home/innoblock/Desktop/free-gas-besu-private/config.yaml
2022.07.19-14:50:03.725 info  [caliper] [cli-launch-manager] 	Set network configuration path: /home/innoblock/Desktop/free-gas-besu-private/network.json
2022.07.19-14:50:03.725 info  [caliper] [cli-launch-manager] 	Set SUT type: ethereum
2022.07.19-14:50:03.970 info  [caliper] [benchmark-validator] 	No observer specified, will default to `none`
2022.07.19-14:50:03.970 info  [caliper] [caliper-engine] 	Starting benchmark flow
2022.07.19-14:50:03.983 info  [caliper] [caliper-engine] 	Skipping start commands due to benchmark flow conditioning
2022.07.19-14:50:03.983 info  [caliper] [caliper-engine] 	Skipping initialization phase due to benchmark flow conditioning
2022.07.19-14:50:03.984 info  [caliper] [caliper-engine] 	Skipping install smart contract phase due to benchmark flow conditioning
2022.07.19-14:50:03.985 info  [caliper] [monitor.js] 	No resource monitors specified
2022.07.19-14:50:03.986 info  [caliper] [default-observer] 	Observer interval set to 5000 seconds
2022.07.19-14:50:03.988 info  [caliper] [round-orchestrator] 	Preparing worker connections
2022.07.19-14:50:03.988 info  [caliper] [worker-orchestrator] 	Launching worker 1 of 1
2022.07.19-14:50:03.991 info  [caliper] [worker-orchestrator] 	Messenger not configured, entering configure phase...
2022.07.19-14:50:03.992 info  [caliper] [worker-orchestrator] 	No existing workers detected, entering worker launch phase...
2022.07.19-14:50:03.992 info  [caliper] [worker-orchestrator] 	Waiting for 1 workers to be connected...
2022.07.19-14:50:04.241 info  [caliper] [cli-launch-worker] 	Set workspace path: /home/innoblock/Desktop/free-gas-besu-private
2022.07.19-14:50:04.242 info  [caliper] [cli-launch-worker] 	Set benchmark configuration path: /home/innoblock/Desktop/free-gas-besu-private/config.yaml
2022.07.19-14:50:04.242 info  [caliper] [cli-launch-worker] 	Set network configuration path: /home/innoblock/Desktop/free-gas-besu-private/network.json
2022.07.19-14:50:04.242 info  [caliper] [cli-launch-worker] 	Set SUT type: ethereum
2022.07.19-14:50:04.501 info  [caliper] [worker-orchestrator] 	1 workers connected, progressing to worker assignment phase.
2022.07.19-14:50:04.501 info  [caliper] [worker-orchestrator] 	Workers currently unassigned, awaiting index assignment...
2022.07.19-14:50:04.501 info  [caliper] [worker-orchestrator] 	Waiting for 1 workers to be assigned...
2022.07.19-14:50:04.524 info  [caliper] [worker-orchestrator] 	1 workers assigned, progressing to worker initialization phase.
2022.07.19-14:50:04.524 info  [caliper] [worker-orchestrator] 	Waiting for 1 workers to be ready...
2022.07.19-14:50:04.538 info  [caliper] [worker-orchestrator] 	1 workers ready, progressing to test preparation phase.
2022.07.19-14:50:04.538 info  [caliper] [round-orchestrator] 	Started round 1 (open)
2022.07.19-14:50:04.556 error [caliper] [round-orchestrator] 	Failed round 1 (open): Error: Error: connection not open on send()
    at WorkerOrchestrator.updateWorkerPhase (/home/innoblock/node_modules/@hyperledger/caliper-core/lib/manager/orchestrators/worker-orchestrator.js:306:61)
    at ProcessMessenger.messenger.on (/home/innoblock/node_modules/@hyperledger/caliper-core/lib/manager/orchestrators/worker-orchestrator.js:109:18)
    at ProcessMessenger.emit (events.js:198:13)
    at ProcessMessenger.onMessage (/home/innoblock/node_modules/@hyperledger/caliper-core/lib/common/messengers/messenger-interface.js:40:14)
    at ChildProcess.workerProcess.on (/home/innoblock/node_modules/@hyperledger/caliper-core/lib/common/messengers/process/process-messenger.js:59:26)
    at ChildProcess.emit (events.js:198:13)
    at emit (internal/child_process.js:832:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
2022.07.19-14:50:04.556 info  [caliper] [round-orchestrator] 	Started round 2 (query)
2022.07.19-14:50:04.569 error [caliper] [round-orchestrator] 	Failed round 2 (query): Error: Error: connection not open on send()
    at WorkerOrchestrator.updateWorkerPhase (/home/innoblock/node_modules/@hyperledger/caliper-core/lib/manager/orchestrators/worker-orchestrator.js:306:61)
    at ProcessMessenger.messenger.on (/home/innoblock/node_modules/@hyperledger/caliper-core/lib/manager/orchestrators/worker-orchestrator.js:109:18)
    at ProcessMessenger.emit (events.js:198:13)
    at ProcessMessenger.onMessage (/home/innoblock/node_modules/@hyperledger/caliper-core/lib/common/messengers/messenger-interface.js:40:14)
    at ChildProcess.workerProcess.on (/home/innoblock/node_modules/@hyperledger/caliper-core/lib/common/messengers/process/process-messenger.js:59:26)
    at ChildProcess.emit (events.js:198:13)
    at emit (internal/child_process.js:832:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
2022.07.19-14:50:04.569 info  [caliper] [round-orchestrator] 	Started round 3 (transfer)
2022.07.19-14:50:04.580 error [caliper] [round-orchestrator] 	Failed round 3 (transfer): Error: Error: connection not open on send()
    at WorkerOrchestrator.updateWorkerPhase (/home/innoblock/node_modules/@hyperledger/caliper-core/lib/manager/orchestrators/worker-orchestrator.js:306:61)
    at ProcessMessenger.messenger.on (/home/innoblock/node_modules/@hyperledger/caliper-core/lib/manager/orchestrators/worker-orchestrator.js:109:18)
    at ProcessMessenger.emit (events.js:198:13)
    at ProcessMessenger.onMessage (/home/innoblock/node_modules/@hyperledger/caliper-core/lib/common/messengers/messenger-interface.js:40:14)
    at ChildProcess.workerProcess.on (/home/innoblock/node_modules/@hyperledger/caliper-core/lib/common/messengers/process/process-messenger.js:59:26)
    at ChildProcess.emit (events.js:198:13)
    at emit (internal/child_process.js:832:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
2022.07.19-14:50:04.581 info  [caliper] [report-builder] 	### All test results ###
2022.07.19-14:50:04.581 error [caliper] [report-builder] 	No data within test result; implies error within configuration files
2022.07.19-14:50:04.582 error [caliper] [round-orchestrator] 	Error while finalizing the report: Error: unrecognized report table
    at ReportBuilder.setSummaryTable (/home/innoblock/node_modules/@hyperledger/caliper-core/lib/manager/report/report-builder.js:142:19)
    at Report.printResultsByRound (/home/innoblock/node_modules/@hyperledger/caliper-core/lib/manager/report/report.js:182:28)
    at RoundOrchestrator.run (/home/innoblock/node_modules/@hyperledger/caliper-core/lib/manager/orchestrators/round-orchestrator.js:230:25)
    at process._tickCallback (internal/process/next_tick.js:68:7)
2022.07.19-14:50:04.582 info  [caliper] [monitor.js] 	Stopping all monitors
2022.07.19-14:50:04.582 info  [caliper] [worker-orchestrator] 	Sending exit message to connected workers
2022.07.19-14:50:04.582 info  [caliper] [round-orchestrator] 	Benchmark finished in 0.044 seconds. Total rounds: 3. Successful rounds: 0. Failed rounds: 3.
2022.07.19-14:50:04.583 info  [caliper] [caliper-engine] 	Skipping end command due to benchmark flow conditioning
2022.07.19-14:50:04.583 info  [caliper] [cli-launch-manager] 	Benchmark successfully finished
innoblock@innoblock-PowerEdge-T140:~/Desktop/free-gas-besu-private$ 2022.07.19-14:50:04.589 info  [caliper] [worker-message-handler] 	Initializing Worker#0...
2022.07.19-14:50:04.589 info  [caliper] [worker-message-handler] 	Worker#0 initialized
2022.07.19-14:50:04.590 info  [caliper] [worker-message-handler] 	Preparing Worker#0 for Round#0
2022.07.19-14:50:04.590 info  [caliper] [caliper-worker] 	Worker [0] encountered an error during prepare test phase for round 0: Error: connection not open on send()
    at Object.ConnectionError (/home/innoblock/node_modules/web3-core-helpers/lib/errors.js:66:23)
    at Object.ConnectionNotOpenError (/home/innoblock/node_modules/web3-core-helpers/lib/errors.js:49:21)
    at /home/innoblock/node_modules/web3-providers-ws/lib/index.js:155:37
    at Map.forEach (<anonymous>)
    at WebsocketProvider._onClose (/home/innoblock/node_modules/web3-providers-ws/lib/index.js:154:27)
    at W3CWebSocket._dispatchEvent [as dispatchEvent] (/home/innoblock/node_modules/yaeti/lib/EventTarget.js:115:12)
    at W3CWebSocket.onConnectFailed (/home/innoblock/node_modules/websocket/lib/W3CWebSocket.js:219:14)
    at WebSocketClient.<anonymous> (/home/innoblock/node_modules/websocket/lib/W3CWebSocket.js:59:25)
    at WebSocketClient.emit (events.js:198:13)
    at WebSocketClient.failHandshake (/home/innoblock/node_modules/websocket/lib/WebSocketClient.js:339:10)
    at ClientRequest.<anonymous> (/home/innoblock/node_modules/websocket/lib/WebSocketClient.js:278:18)
    at ClientRequest.emit (events.js:198:13)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:565:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:111:17)
    at Socket.socketOnData (_http_client.js:451:20)
    at Socket.emit (events.js:198:13)
2022.07.19-14:50:04.590 info  [caliper] [caliper-worker] 	Info: worker 0 prepare test phase for round 0 is completed
2022.07.19-14:50:04.590 error [caliper] [worker-message-handler] 	Error while handling "prepare" message for Worker (14122): Error: connection not open on send()
    at Object.ConnectionError (/home/innoblock/node_modules/web3-core-helpers/lib/errors.js:66:23)
    at Object.ConnectionNotOpenError (/home/innoblock/node_modules/web3-core-helpers/lib/errors.js:49:21)
    at /home/innoblock/node_modules/web3-providers-ws/lib/index.js:155:37
    at Map.forEach (<anonymous>)
    at WebsocketProvider._onClose (/home/innoblock/node_modules/web3-providers-ws/lib/index.js:154:27)
    at W3CWebSocket._dispatchEvent [as dispatchEvent] (/home/innoblock/node_modules/yaeti/lib/EventTarget.js:115:12)
    at W3CWebSocket.onConnectFailed (/home/innoblock/node_modules/websocket/lib/W3CWebSocket.js:219:14)
    at WebSocketClient.<anonymous> (/home/innoblock/node_modules/websocket/lib/W3CWebSocket.js:59:25)
    at WebSocketClient.emit (events.js:198:13)
    at WebSocketClient.failHandshake (/home/innoblock/node_modules/websocket/lib/WebSocketClient.js:339:10)
    at ClientRequest.<anonymous> (/home/innoblock/node_modules/websocket/lib/WebSocketClient.js:278:18)
    at ClientRequest.emit (events.js:198:13)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:565:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:111:17)
    at Socket.socketOnData (_http_client.js:451:20)
    at Socket.emit (events.js:198:13)
2022.07.19-14:50:04.590 info  [caliper] [worker-message-handler] 	Preparing Worker#0 for Round#1
2022.07.19-14:50:04.590 info  [caliper] [caliper-worker] 	Worker [0] encountered an error during prepare test phase for round 1: Error: connection not open on send()
    at Object.ConnectionError (/home/innoblock/node_modules/web3-core-helpers/lib/errors.js:66:23)
    at Object.ConnectionNotOpenError (/home/innoblock/node_modules/web3-core-helpers/lib/errors.js:49:21)
    at WebsocketProvider.send (/home/innoblock/node_modules/web3-providers-ws/lib/index.js:269:33)
    at RequestManager.send (/home/innoblock/node_modules/web3-core-requestmanager/lib/index.js:147:23)
    at sendRequest (/home/innoblock/node_modules/web3-core-method/lib/index.js:609:42)
    at Eth.send [as getGasPrice] (/home/innoblock/node_modules/web3-core-method/lib/index.js:636:13)
    at EthereumConnector.getContext (/home/innoblock/node_modules/@hyperledger/caliper-ethereum/lib/ethereum-connector.js:158:35)
    at CaliperWorker.prepareTest (/home/innoblock/node_modules/@hyperledger/caliper-core/lib/worker/caliper-worker.js:156:50)
    at WorkerMessageHandler._handlePrepareMessage (/home/innoblock/node_modules/@hyperledger/caliper-core/lib/worker/worker-message-handler.js:210:31)
    at ProcessMessenger.WorkerMessageHandler.messenger.on (/home/innoblock/node_modules/@hyperledger/caliper-core/lib/worker/worker-message-handler.js:89:24)
    at ProcessMessenger.emit (events.js:198:13)
    at ProcessMessenger.onMessage (/home/innoblock/node_modules/@hyperledger/caliper-core/lib/common/messengers/messenger-interface.js:40:14)
    at process.workerProcess.on (/home/innoblock/node_modules/@hyperledger/caliper-core/lib/common/messengers/process/process-messenger.js:59:26)
    at process.emit (events.js:198:13)
    at emit (internal/child_process.js:832:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
2022.07.19-14:50:04.590 info  [caliper] [caliper-worker] 	Info: worker 0 prepare test phase for round 1 is completed
2022.07.19-14:50:04.590 error [caliper] [worker-message-handler] 	Error while handling "prepare" message for Worker (14122): Error: connection not open on send()
    at Object.ConnectionError (/home/innoblock/node_modules/web3-core-helpers/lib/errors.js:66:23)
    at Object.ConnectionNotOpenError (/home/innoblock/node_modules/web3-core-helpers/lib/errors.js:49:21)
    at WebsocketProvider.send (/home/innoblock/node_modules/web3-providers-ws/lib/index.js:269:33)
    at RequestManager.send (/home/innoblock/node_modules/web3-core-requestmanager/lib/index.js:147:23)
    at sendRequest (/home/innoblock/node_modules/web3-core-method/lib/index.js:609:42)
    at Eth.send [as getGasPrice] (/home/innoblock/node_modules/web3-core-method/lib/index.js:636:13)
    at EthereumConnector.getContext (/home/innoblock/node_modules/@hyperledger/caliper-ethereum/lib/ethereum-connector.js:158:35)
    at CaliperWorker.prepareTest (/home/innoblock/node_modules/@hyperledger/caliper-core/lib/worker/caliper-worker.js:156:50)
    at WorkerMessageHandler._handlePrepareMessage (/home/innoblock/node_modules/@hyperledger/caliper-core/lib/worker/worker-message-handler.js:210:31)
    at ProcessMessenger.WorkerMessageHandler.messenger.on (/home/innoblock/node_modules/@hyperledger/caliper-core/lib/worker/worker-message-handler.js:89:24)
    at ProcessMessenger.emit (events.js:198:13)
    at ProcessMessenger.onMessage (/home/innoblock/node_modules/@hyperledger/caliper-core/lib/common/messengers/messenger-interface.js:40:14)
    at process.workerProcess.on (/home/innoblock/node_modules/@hyperledger/caliper-core/lib/common/messengers/process/process-messenger.js:59:26)
    at process.emit (events.js:198:13)
    at emit (internal/child_process.js:832:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
2022.07.19-14:50:04.590 info  [caliper] [worker-message-handler] 	Preparing Worker#0 for Round#2
2022.07.19-14:50:04.590 info  [caliper] [caliper-worker] 	Worker [0] encountered an error during prepare test phase for round 2: Error: connection not open on send()
    at Object.ConnectionError (/home/innoblock/node_modules/web3-core-helpers/lib/errors.js:66:23)
    at Object.ConnectionNotOpenError (/home/innoblock/node_modules/web3-core-helpers/lib/errors.js:49:21)
    at WebsocketProvider.send (/home/innoblock/node_modules/web3-providers-ws/lib/index.js:269:33)
    at RequestManager.send (/home/innoblock/node_modules/web3-core-requestmanager/lib/index.js:147:23)
    at sendRequest (/home/innoblock/node_modules/web3-core-method/lib/index.js:609:42)
    at Eth.send [as getGasPrice] (/home/innoblock/node_modules/web3-core-method/lib/index.js:636:13)
    at EthereumConnector.getContext (/home/innoblock/node_modules/@hyperledger/caliper-ethereum/lib/ethereum-connector.js:158:35)
    at CaliperWorker.prepareTest (/home/innoblock/node_modules/@hyperledger/caliper-core/lib/worker/caliper-worker.js:156:50)
    at WorkerMessageHandler._handlePrepareMessage (/home/innoblock/node_modules/@hyperledger/caliper-core/lib/worker/worker-message-handler.js:210:31)
    at ProcessMessenger.WorkerMessageHandler.messenger.on (/home/innoblock/node_modules/@hyperledger/caliper-core/lib/worker/worker-message-handler.js:89:24)
    at ProcessMessenger.emit (events.js:198:13)
    at ProcessMessenger.onMessage (/home/innoblock/node_modules/@hyperledger/caliper-core/lib/common/messengers/messenger-interface.js:40:14)
    at process.workerProcess.on (/home/innoblock/node_modules/@hyperledger/caliper-core/lib/common/messengers/process/process-messenger.js:59:26)
    at process.emit (events.js:198:13)
    at emit (internal/child_process.js:832:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
2022.07.19-14:50:04.591 info  [caliper] [caliper-worker] 	Info: worker 0 prepare test phase for round 2 is completed
2022.07.19-14:50:04.591 error [caliper] [worker-message-handler] 	Error while handling "prepare" message for Worker (14122): Error: connection not open on send()
    at Object.ConnectionError (/home/innoblock/node_modules/web3-core-helpers/lib/errors.js:66:23)
    at Object.ConnectionNotOpenError (/home/innoblock/node_modules/web3-core-helpers/lib/errors.js:49:21)
    at WebsocketProvider.send (/home/innoblock/node_modules/web3-providers-ws/lib/index.js:269:33)
    at RequestManager.send (/home/innoblock/node_modules/web3-core-requestmanager/lib/index.js:147:23)
    at sendRequest (/home/innoblock/node_modules/web3-core-method/lib/index.js:609:42)
    at Eth.send [as getGasPrice] (/home/innoblock/node_modules/web3-core-method/lib/index.js:636:13)
    at EthereumConnector.getContext (/home/innoblock/node_modules/@hyperledger/caliper-ethereum/lib/ethereum-connector.js:158:35)
    at CaliperWorker.prepareTest (/home/innoblock/node_modules/@hyperledger/caliper-core/lib/worker/caliper-worker.js:156:50)
    at WorkerMessageHandler._handlePrepareMessage (/home/innoblock/node_modules/@hyperledger/caliper-core/lib/worker/worker-message-handler.js:210:31)
    at ProcessMessenger.WorkerMessageHandler.messenger.on (/home/innoblock/node_modules/@hyperledger/caliper-core/lib/worker/worker-message-handler.js:89:24)
    at ProcessMessenger.emit (events.js:198:13)
    at ProcessMessenger.onMessage (/home/innoblock/node_modules/@hyperledger/caliper-core/lib/common/messengers/messenger-interface.js:40:14)
    at process.workerProcess.on (/home/innoblock/node_modules/@hyperledger/caliper-core/lib/common/messengers/process/process-messenger.js:59:26)
    at process.emit (events.js:198:13)
    at emit (internal/child_process.js:832:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
2022.07.19-14:50:04.591 info  [caliper] [worker-message-handler] 	Worker#0 is exiting
```

### Please provide your benchmark configuration file content, if possible.

```yaml
simpleArgs: &simple-args
  initialMoney: 10000
  moneyToTransfer: 100
  numberOfAccounts: &number-of-accounts 1000

test:
  name: simple
  description: >-
    This is an example benchmark for Caliper, to test the backend DLT's
    performance with simple account opening & querying transactions.
  workers:
    number: 1
  rounds:
    - label: open
      description: >-
        Test description for the opening of an account through the deployed
        contract.
      txNumber: *number-of-accounts
      rateControl:
        type: fixed-rate
        opts:
          tps: 50
      workload:
        module: simple/open.js
        arguments: *simple-args
    - label: query
      description: Test description for the query performance of the deployed contract.
      txNumber: *number-of-accounts
      rateControl:
        type: fixed-rate
        opts:
          tps: 100
      workload:
        module: simple/query.js
        arguments: *simple-args
    - label: transfer
      description: Test description for transfering money between accounts.
      txNumber: 50
      rateControl:
        type: fixed-rate
        opts:
          tps: 5
      workload:
        module: simple/transfer.js
        arguments:
          << : *simple-args
          money: 100
```

### Please provide your network configuration file content, if possible.

```yaml
{
    "caliper":  {
        "blockchain": "ethereum",
        "command" : {}
    },
    "ethereum": {
        "url": "ws://localhost:8546",
        "contractDeployerAddress":"0x627306090abaB3A6e1400e9345bC60c78a8BEf57",
        "contractDeployerAddressPrivateKey": "0xc87509a1c067bbde78beb793e6fa76530b6382a4c0241e5e4a9ec0a0f44dc0d3",
        "fromAddress":"0x627306090abaB3A6e1400e9345bC60c78a8BEf57",
        "fromAddressPrivateKey": "0xc87509a1c067bbde78beb793e6fa76530b6382a4c0241e5e4a9ec0a0f44dc0d3",
        "transactionConfirmationBlocks": 2,
        "contracts": {
            "address":"0xF328c11c4dF88d18FcBd30ad38d8B4714F4b33bF",
            "simple": {
                "path": "simple.json",
                "estimateGas": true,
                "gas": {
                    "open": 45000,
                    "query": 100000,
                    "transfer": 70000
                }
            }
        }
    }
}
```

### Please provide your workload module content, if possible.

```nodejs
I got open.js, query,js, and transfer.js from the repository.

I also created simple.json.
{
    "name": "simple",
    "abi": [{"inputs":[{"internalType":"uint256"...],
    "bytecode":"608060405234801562000011...",
    "gas": 859653
}
```

### Please provide any additional information you deem relevant to the error.
I use the following command.
npx caliper launch manager --caliper-workspace . --caliper-benchconfig config.yaml  --caliper-networkconfig network.json --caliper-flow-only-test=true

**Comment by davidkel** [comment]
Closing as support for besu and ethereum have now been dropped
