### ISSUE TITLE
Unit tests for caliper-ethereum

### ISSUE THREAD

**Issue by davidkel** [hyperledger-caliper/caliper#1556]
This package has no unit tests at all
New tests should not assume that the code is actually correct. It's expected that if the tests finds bugs or relevant situations where unexpected behaviour occurs then the code should also be fixed.

**Comment by Sweetdevil144** [comment]
Hey @davidkel . I'd like to work on this issue if this is available !

**Comment by davidkel** [comment]
@Sweetdevil144 I've assigned it to you

**Comment by davidkel** [comment]
@Sweetdevil144 all I can suggest is review how the caliper-fabric does it's tests. I'm not actually familiar with the ethereum package sorry. The caliper-fabric tests are the pattern to follow.

**Comment by Sweetdevil144** [comment]
Created tests for `connector-Factory.js`. I'm trying to create tests for `ethereum-connector.js` but it keeps throwing logs as below when I logged the info as follow : 
```javascript
let configPath = CaliperUtils.resolvePath(ConfigUtil.get(ConfigUtil.keys.NetworkConfig));
        console.log(`Config Path: ${configPath}`);
        let ethereumConfig;
        try {
            ethereumConfig = require(configPath).ethereum;
        } catch (error) {
            console.error(`Error requiring configPath: ${error}`);
            throw error;
        }
```

Original code lines were as follow : https://github.com/hyperledger/caliper/blob/ae23774d7bba51b55980cdc9110b11729aab96f7/packages/caliper-ethereum/lib/ethereum-connector.js#L46

Error logs :
```
 TypeError [ERR_INVALID_ARG_TYPE]: The "id" argument must be of type string. Received undefined
at Module.require (node:internal/modules/cjs/loader:1223:3)
      at require (node:internal/modules/helpers:179:18)
      at new EthereumConnector (lib/ethereum-connector.js:50:30)
      at Context.<anonymous> (test/ethereum-connector.js:100:27)
      at process.processImmediate (node:internal/timers:478:21)
```

Take a look at my current test file from : [here](https://github.com/Sweetdevil144/caliper/blob/develop/packages/caliper-ethereum/test/ethereum-connector.js) to know how I'm mocking the data. (I found some test network configs for ethereum pre-created, utilising the same for now).

**Comment by davidkel** [comment]
Closing as we have had to drop ethereum and besu support

**Comment by Sweetdevil144** [comment]
I almost forgot about this due to a busy schedule. Do you want me to close the 2 linked PRs as well? Should I focus on new testing mechanisms?
