### ISSUE TITLE
add more info to the error message

### ISSUE THREAD

**Issue by victoryeo** [hyperledger-caliper/caliper#1603]
### Please share the technical limitation of Caliper that you encountered.

when running benchmark, error occur "not found"
please add more information to explain what is not found.

2024.07.23-16:29:04.795 info  [caliper] [caliper-worker] 	Info: worker 0 prepare test phase for round 0 is completed
2024.07.23-16:29:04.796 error [caliper] [worker-message-handler] 	Error while handling "prepare" message for Worker (214732): Error: Returned error: Not Found
    at Object.ErrorResponse (/home/vic/workspace/settlemint/besu-benchmarks/caliper-benchmarks/node_modules/web3-core-helpers/lib/errors.js:28:19)
    at Object.callback (/home/vic/workspace/settlemint/besu-benchmarks/caliper-benchmarks/node_modules/web3-core-requestmanager/lib/index.js:288:36)
    at /home/vic/workspace/settlemint/besu-benchmarks/caliper-benchmarks/node_modules/web3-providers-ws/lib/index.js:114:45
    at Array.forEach (<anonymous>)
    at WebsocketProvider._onMessage (/home/vic/workspace/settlemint/besu-benchmarks/caliper-benchmarks/node_modules/web3-providers-ws/lib/index.js:102:69)
    at W3CWebSocket._dispatchEvent [as dispatchEvent] (/home/vic/workspace/settlemint/besu-benchmarks/caliper-benchmarks/node_modules/yaeti/lib/EventTarget.js:115:12)
    at W3CWebSocket.onMessage (/home/vic/workspace/settlemint/besu-benchmarks/caliper-benchmarks/node_modules/websocket/lib/W3CWebSocket.js:234:14)
    at WebSocketConnection.<anonymous> (/home/vic/workspace/settlemint/besu-benchmarks/caliper-benchmarks/node_modules/websocket/lib/W3CWebSocket.js:205:19)
    at WebSocketConnection.emit (node:events:519:28)
    at WebSocketConnection.processFrame (/home/vic/workspace/settlemint/besu-benchmarks/caliper-benchmarks/node_modules/websocket/lib/WebSocketConnection.js:554:26)
    at /home/vic/workspace/settlemint/besu-benchmarks/caliper-benchmarks/node_modules/websocket/lib/WebSocketConnection.js:323:40
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)
2024.07.23-16:29:04.799 error [caliper] [round-orchestrator] 	Failed round 1 (50 txns with 1tps): Error: Error: Returned error: Not Found

### Please detail your feature idea that could alleviate the limitation.

please add more information to explain what is not found.

**Comment by davidkel** [comment]
Closing as support for Besu has been dropped
